### ISSUE TITLE
設計書

### ISSUE THREAD

**Issue by RichardRoe1234** [RichardRoe1234/Questionnaire#1]
![DSC_0370](https://user-images.githubusercontent.com/50108810/68669291-88b03b80-058d-11ea-830f-1600bda612ea.jpg)

**Comment by g00cey** [comment]
画像が見えない。
issue=問題点で終わったら消すもの　つまり設計書は消すものではないのでissueに登録するべきものではない。
issueはタスクとしてこれやるあれやるはOKだけど、設計書置き場としては不適格。
